# Generated by Django 3.2.25 on 2024-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
