# Generated by Django 3.2.25 on 2024-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0002_personas_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='activo',
            field=models.CharField(default='s', max_length=2),
        ),
    ]
