# Generated by Django 3.2.25 on 2024-12-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0003_personas_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosvuelos',
            old_name='idCiudadOrigen',
            new_name='idPasajero',
        ),
    ]
