# Generated by Django 3.2.25 on 2024-12-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0005_personas_adolfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='idDireccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebadb.direccion'),
        ),
    ]
